[package]
name = "request-atlas"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "request_atlas_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.22", features = ["macos-private-api"] }
tauri-plugin-shell = "2.0.0-beta.7"
tauri-plugin-window-state = "2.0.0-beta.9"
serde_json = "1.0.118"
tauri-plugin-store = "2.0.0-beta.8"
tauri-plugin-http = "2.0.0-beta.10"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
